catalog_templating/render.py
Idea is to have all values coming from the user under one key.
This makes it easier to pass the whole context to a function for validation, normalization or other processing.
In addition makes it easier to "dump" the data while developing in order to see the contents.
This should allow later to pass extra keys without risking overriding any user values.
eg ix_app_context, etc.
To be fair, I don't expect this to be the case.
PS. Is this function going to be used in production too? If not, we should also adapt the production side as-well.
=> move values under "values" key

apps_ci/scripts/catalog_update.py
We have a publish action whose usecase is to publish any apps which have been updated in our dev workflow for apps. However if no app update has been made and we attempt to publish it errors out saying relevant version already exists. This should be a safe operation.
If a version has been published already, let's not attempt to do that again hence making the publish action safe to use in the CI.
=> NAS-129729 / 24.10 / Do not error out if no app is to be published

apps_ci/scripts/catalog_update.py
Properly check if version bump is required for an app when we are publishing them.
=> NAS-129729 / 24.10 / Properly check if version has been bumped for an app

catalog_reader/app.py
This commit adds changes to include version key when retrieving app details with human version to make it easy when management tasks are being performed on apps like app upgrade/rollback etc
=> NAS-129962 / 24.10 / Include version key when retrieving app details

apps_schema/features/basic.py, apps_schema/features/certificate.py, apps_schema/features/container_image.py, apps_schema/features/interface.py, apps_schema/features/node.py
As we have moved over to docker and python - we are updating casing in the features definition so that they can be used instead of the camelcase we had in place reflecting golang/helm's primary casing preference.
=> NAS-130046 / 24.10 / Fix apps schema features casing

apps_schema/features/node.py, catalog_reader/app_utils.py, catalog_reader/questions.py
Remove `validations/node_port` feature as it's not being used anymore and `definitions/port` already automatically enforces that unused ports get consumed.
Adjust node ip ref to actually show all the ips available on the host which the app can bind to.
=> NAS-130170 / 24.10 / Fix node_ip feature

apps_validation/portals.py, apps_validation/validate_templates.py
Validate specified portals and notes in rendered compose file.
=> NAS-130172 / 24.10 / Validate specified portals and notes

catalog_reader/app_utils.py, catalog_reader/questions.py
This PR adds changes so GPU refs are properly rendered.
=> NAS-130121 / 24.10 / Render GPU feature

catalog_reader/questions_util.py
For ix volumes, expose a force flag which will allow to apply ACLs even if the path has existing data - this would be useful for the case if ACLs are changed for a path later on and the ix volume in question already has data inside.
=> NAS-130171 / 24.10 / Allow force flag for ACLs being applied on ix volumes

catalog_templating/scripts/render_compose.py
It would be nice if we can have some values constant and not specified in questions.yaml i.e image values. This is similar to what we had with `ix_values.yaml` in k8s implementation, after discussing with Stavros that change has been made here as well so we can have such values separately and added when we render compose file.
=> NAS-130323 / 24.10 / Make sure ix_values.yaml file is provided to compose rendering if it exists

apps_validation/validate_templates.py
Using `ix_values.yaml` works for render, but seems to fail validations
https://github.com/truenas/apps/actions/runs/10166994937/job/28118569064
I think we are not loading the values during the validation.
More context:
https://github.com/truenas/apps_validation/pull/38
=> fix validation

apps_ci/scripts/catalog_update.py, catalog_reader/app.py, catalog_reader/catalog.py
Currently, catalog updates are generating app caches with normalized question schemas. This normalization is not needed in the cache as it increases the size of the cache file and is totally irrelevant and redundant.
Make changes to avoid normalizing the question schema while generating app versions cache files.
=> NAS-130223 / 24.10 / Don't normalize apps versions data while caching

apps_validation/validate_app_version.py, apps_validation/validate_k8s_to_docker_migration.py
Kubernetes to Docker migration validation is not currently included in app_validation. The migration script must contain a shebang at the start and must be executable.
Add validation for the Kubernetes to Docker migration file at the app level to ensure the migration file is executable and contains a shebang at the start.
=> NAS-130250 / 24.10 / Validate k8s to docker migration file

apps_ci/scripts/catalog_update.py, apps_validation/json_schema_utils.py, apps_validation/validate_app.py
Having `screenshots/categories` keys in app's `app.yaml` is not a requirement but if they were added by app dev, we were not validating them. In this case misconfigured values for them have been added which is causing CI to fail and apps_validation should be catching this sooner.
Properly make sure the app being validated in question is validated properly for these extra keys as well.
=> NAS-130449 / 24.10 / Improve validation for apps

catalog_reader/app_utils.py, catalog_reader/questions.py
This commit adds changes to provide min/max for port ref and no longer populates an enum.
=> NAS-130493 / 24.10 / Provide min/max for port ref

catalog_reader/app.py, catalog_reader/custom_app.py
This PR adds support for a custom app which essentially will be a custom provided docker compose file from the user.
=> NAS-130496 / 24.10 / Add support for deploying custom apps

catalog_reader/app.py
Problem:
Markdown (and html) ignores single new lines.
To make it easier to layout long paragraphs in multiple lines
But when we convert `md` to `html` and them to `json`, those new lines are encoded in to the string and UI will actually render the new line.
If we take the output `markdown.markdown` and directly write it to `html`, it will display correctly (ignoring single new lines).
But because we then place it in a `json` which encodes the new lines in, then the output displays the new lines
Solution:
Replace the `\n` to ` `. This makes the UI render correctly the README, without developer having to constantly think how to write the readme files.
More context:
https://ixsystems.atlassian.net/jira/software/c/projects/TNCHARTS/issues/TNCHARTS-1305
=> produce cleaner markdown from readme

apps_ci/images_info.py, apps_ci/scripts/bump_version.py
We need to also update the `app_version` field as well if the main image is updated
=> extend bump version script

apps_ci/scripts/bump_version.py, apps_ci/version_bump.py
Makes bumping version in CI optional.
Reasoning is that renovate calls this script on each dep update.
For example if an app have multiple containers, it will call it for each one of them.
That by itself is not an issue as wrap it in a bash script and call it once.
https://github.com/truenas/apps/blob/18c3dbfaf58341166c599b578ecf03ff4bc71d09/.github/scripts/renovate_bump.sh#L23-L25
However that means that if renovate calls the script FIRST for a container that is not the "main" container.
The app_version will never be bumped.
Solution is to call this script on every container, but only bump once.
This is paired with https://github.com/truenas/apps/pull/410
=> ci: make bump optional

apps_schema/attrs/base.py
We are missing validation in the case when default values are not present in the enum options.
Implement validation to ensure that default values are included within the enum options.
=> NAS-130790 / 25.04 / Validate default values exist in the enum specified in the schema

.github/workflows/tests.yml, apps_ci/pytest/unit/test_get_apps_to_publish.py, apps_ci/pytest/unit/test_get_changed_app.py, apps_ci/pytest/unit/test_is_main_dep.py, apps_ci/pytest/unit/test_publish_updated_apps.py, apps_ci/pytest/unit/test_rename_versioned_dir.py, apps_ci/pytest/unit/test_update_app_version.py, apps_ci/pytest/unit/test_update_catalog_file.py
This commit adds unit tests for apps ci package testing various aspects of the different scripts and utils we have which are used for development and deploying of apps.
=> NAS-131884 / 25.04 / Add unit tests for apps ci package

catalog_templating/render.py
Using `os.listdir`, `pathlib.Path.iterdir`, `os.path.isfile` and `pathlib.Path.is_file` in the same file is strange and inconsistent. Simplify the for loops and use the much more performant `os.scandir` when iterating directories.
=> NAS-133204 / 25.04 / fix, simplify, and speed-up render.py

apps_validation/json_schema_utils.py, apps_validation/pytest/unit/test_app_validate.py, apps_validation/validate_app_version.py, apps_validation/validate_migrations.py
We are adding support for app config migrations and changes have been made to make sure that catalog conforms to expected format which is required for app migrations to be executed.
=> NAS-133616 / 25.04 / Add logic to validate app migrations

apps_validation/json_schema_utils.py, catalog_reader/app.py
We have `chart_metadata` key being used to determine min/max scale version check on apps and as we are moving on to adding migrations which will only work in FT, we want to make sure users in EE are not able to consume these versions of the apps as migrations won't run in EE. 
So temporarily we are adding `chart_metadata` key there so anybody in EE trying to upgrade to these app versions which require migrations to function, has no issues and a nice error is displayed to them.
=> NAS-133964 / 25.10 / Add chart_metadata to generated app versions file

apps_schema/features/certificate.py, catalog_reader/pytest/unit/test_normalize_questions.py, catalog_reader/questions.py
This PR adds changes to remove `certificate_authorities` ref from apps validation, we would be making relevant changes in middleware as well in a different PR (same ticket, so these are merged together). This has never been used in our new apps implementation and as we are removing CA plugin, we are removing the support for the ref as well.
=> NAS-133957 / 25.10 / Remove certificate authority ref from apps validation

apps_ci/pytest/unit/test_update_catalog_file.py, apps_validation/json_schema_utils.py, apps_validation/pytest/unit/test_app_validate.py
Adds 2 fields.
- `changelog_url`. Which will always be optional, as not upstreams have one.
- `date_added`: Which will hold the initial date an app is added. Useful in order to have a "recently added" section.
=> Add extra fields in annotations

apps_ci/scripts/catalog_update.py
Reverts truenas/apps_validation#73
Apparently we are re-validating that an app renders right before we update the catalog.
Reverting this to fix catalog, until we figure a better way
```
Entry: catalog_update.py (arg update) ->
Func chain:
update_catalog_file ->
get_trains ->
retrieve_trains_data ->
app_details ->
get_app_details ->
validate_catalog_item ->
validate_catalog_item_version ->
validate_templates ->
validate_template_rendering
```
FIxes https://github.com/truenas/apps/issues/2295
=> Revert "dont copy test-files in published apps"
